url: "https://blog.meshcore.io"
baseurl: ""
title: "MeshCore Blog"
subtitle: "Posts from the MeshCore Developers"
description: "Posts from the MeshCore Developers"
image: "assets/images/icon.png"
permalink: ":year/:month/:day/:title"

logo: "assets/images/icon.png"

authors:
  admin:
    name: "Admin"
    title: "Site Admin"
    avatar: "assets/images/authors/admin.png"
  liamcottle:
    name: "Liam Cottle"
    title: "MeshCore App Developer"
    avatar: "assets/images/authors/liamcottle.jpg"
    donate_url: "https://github.com/sponsors/liamcottle"
  scottpowell:
    name: "Scott Powell"
    title: "Lead Firmware Developer"
    avatar: "assets/images/authors/scottpowell.jpg"
    donate_url: "https://buymeacoffee.com/ripplebiz"
  recrof:
    name: "Rastislav Vysoky (recrof)"
    title: "Web/Firmware Developer"
    avatar: "assets/images/authors/rastislavvysoky.jpeg"
    donate_url: "https://github.com/sponsors/recrof?frequency=one-time&sponsor=recrof"

# social links
discord_url: "https://discord.gg/APQSQZNV7t"
github_url: "https://github.com/liamcottle"
twitter_url: "https://twitter.com/liamcottle"
contact_url: "https://liamcottle.com/contact"
linkedin_url: "https://www.linkedin.com/in/liamcottle/"
paypal_url: "https://paypal.me/liamcarncottle"

plugins:
  - jekyll-feed
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - vendor
  - CNAME
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
